FORMAT: 1A

# FUNSys

Polls is a simple API allowing consumers to view polls and vote in them.

## Lectures Collection [/lectures]

### List All Lectures [GET]

+ Response 200 (application/json)

        [
            {
                "lecture_id": "1",
                "disp_lecture": "函館未来学",
                "must": "true",
                "week": "1",
                "jigen": "1",
                "teachers": [
                    "1010001",
                    "1010002",
                    "1010003",
                ],
                "rooms": [
                    "1345",
                    "1123",
                ],
                "classes": [
                    "11",
                    "12",
                    "13",
                    "14"
                ]
            },
            {
                "lecture_id": "2",
                "disp_lecture": "情報アーキテクチャ演習",
                "must": "true",
                "week": "1",
                "jigen": "1",
                "teachers": [
                    "1010003",
                    "1010004",
                ],
                "rooms": [
                    "0791"
                ],
                "classes": [
                    "32",
                    "34"
                ]
            }
        ]


## Lectures Collection [/lectures/{id}]

### List All Lectures [GET]

+ Response 200 (application/json)

        {
            "lecture_id": "1",
            "disp_lecture": "函館未来学",
            "must": "true",
            "week": "1",
            "jigen": "1",
            "teachers": [
                "1010001",
                "1010002",
                "1010003",
            ],
            "rooms": [
                "1345",
                "1123",
            ],
            "classes": [
                "11",
                "12",
                "13",
                "14"
            ]
        }
        
## Classes Collection [/classes]

### List All Classes [GET]

+ Response 200 (application/json)

        [
            {
                "class_id": "11",
                "year": "1",
                "kumi": "A",
                "course": "0"
            },
            {
                "class_id": "12",
                "year": "1",
                "kumi": "B",
                "course": "0"
            },
                        {
                "class_id": "21",
                "year": "2",
                "kumi": "A",
                "course": "1"
            }
        ]
        
## Classes Collection [/classes/{id}]

### List All Classes [GET]

+ Response 200 (application/json)

        {
            "class_id": "11",
            "year": "1",
            "kumi": "A",
            "course": "0"
        }

## Teachers Collection [/teachers]

### List All Teachers [GET]

+ Response 200 (application/json)

        [
            {
                "teacher_id": "1234",
                "disp_teacher": "函館太郎",
                "research_area": "認知科学",
                "course": "1"
            },
            {
                "teacher_id": "5678",
                "disp_teacher": "未来次郎",
                "research_area": "ソフトウェア工学",
                "course": "3"
            }
        ]
                
## Teachers Collection [/teachers/{id}]

### List All Teachers [GET]

+ Response 200 (application/json)

        {
            "teacher_id": "1234",
            "disp_teacher": "函館太郎",
            "research_area": "認知科学",
            "course": "1"
        }
        
## Rooms Collection [/rooms]

### List All Rooms [GET]

+ Response 200 (application/json)

        [
            {
                "room_id": "1234",
                "disp_room": "アトリエ",
            },
            {
                "room_id": "5678",
                "disp_room": "R791",
            },
            {
                "room_id": "9012",
                "disp_room": "大講義室",
            }
        ]

## Rooms Collection [/rooms/{id}]

### List All Rooms [GET]

+ Response 200 (application/json)

        {
            "room_id": "1234",
            "disp_room": "アトリエ",
        }