FORMAT: 1A

# FUNSys

Polls is a simple API allowing consumers to view polls and vote in them.

## Lectures Collection [/lectures]

### List All Lectures [GET]

+ Response 200 (application/json)

        [
            {
                "lecture_id": 1,
                "disp_lecture": "函館未来学",
                "must": {
                    "ICT": "必修",
                    "System": "選択",
                    "Design": "",
                    "Complex": "",
                    "Intelligent": "",
                    "unassign":""
                },
                "week": 1,
                "jigen": 1,
                "teachers": [
                    1,
                    2
                ],
                "rooms": [
                    1,
                    2
                ],
                "classes": [
                    101,
                    212,
                    306
                ]
            },
            {
                "lecture_id": 2,
                "disp_lecture": "情報アーキテクチャ演習",
                "must": {
                    "ICT": "必修",
                    "System": "選択",
                    "Design": "",
                    "Complex": "",
                    "Intelligent": "",
                    "unassign":""
                },
                "week": 2,
                "jigen": 2,
                "teachers": [
                    1,
                    2
                ],
                "rooms": [
                    1
                ],
                "classes": [
                    101
                ]
            }
        ]


## Lectures Collection [/lectures/{id}]

### Single Lectures [GET]

+ Response 200 (application/json)

        {
            "lecture_id": 1,
            "disp_lecture": "函館未来学",
            "must": {
                "ICT": "必修",
                "System": "選択",
                "Design": "",
                "Complex": "",
                "Intelligent": "",
                "unassign":""
            },
            "week": 1,
            "jigen": 1,
            "teachers": [
                1,
                2
            ],
            "rooms": [
                1,
                2
            ],
            "classes": [
                101,
                212,
                306
            ]
        }
        
## Classes Collection [/classes]

### List All Classes [GET]

+ Response 200 (application/json)

        [
            {
                "class_id": 101,
                "disp_class": "1A",
                "course": 0 
            },
            {
                "class_id": 212,
                "disp_class": "2L",
                "course": 4 
            },
            {
                "class_id": 306,
                "disp_class": "3F",
                "course": 2 
            }
        ]
        
## Classes Collection [/classes/{id}]

### Single Classes [GET]

+ Response 200 (application/json)

        {
                "class_id": 101,
                "disp_class": "1A",
                "course": 0 
        }

## Teachers Collection [/teachers]

### List All Teachers [GET]

+ Response 200 (application/json)

        [
            {
                "teacher_id": 1,
                "disp_teacher": "函館太郎",
                "roma_name": "taro hakdoate",
                "position": "准教授",
                "research_area": "認知科学",
                "role": "メタ学習ラボ"
            },
            {
                "teacher_id": 2,
                "disp_teacher": "函館花子",
                "roma_name": "hanako hakdoate",
                "position": "教授",
                "research_area": "システム工学",
                "role": "情報アーキテクチャ"
            }
        ]
                
## Teachers Collection [/teachers/{id}]

### Single Teachers [GET]

+ Response 200 (application/json)

        {
            "teacher_id": 1,
            "disp_teacher": "函館太郎",
            "roma_name": "taro hakdoate",
            "position": "准教授",
            "research_area": "認知科学",
            "role": "情報アーキテクチャ"
        }
        
## Rooms Collection [/rooms]

### List All Rooms [GET]

+ Response 200 (application/json)

        [
            {
                "room_id": 1,
                "disp_room": "アトリエ"
            },
            {
                "room_id": 2,
                "disp_room": "R791"
            },
            {
                "room_id": 3,
                "disp_room": "大講義室"
            }
        ]

## Rooms Collection [/rooms/{id}]

### Single Rooms [GET]

+ Response 200 (application/json)

        {
            "room_id": 1,
            "disp_room": "アトリエ"
        }